os:
  - linux
  - osx
sudo: false
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh
  - nvm install 0.10
  - nvm install 4.2
  - nvm install 5.5
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - nvm exec 5.5 npm install
script:
  - nvm run 5.5 test.js
  - nvm run 4.2 test.js
  - nvm run 0.10 test.js
  - nvm run 4.2 test.js
  - nvm run 5.5 test.js
